### ISSUE TITLE
If Archetype has required fields, the property can't be optional

### ISSUE THREAD

**Issue by tomfulton** [kgiszewski/Archetype#68] opened 2014-02-28 01:04 UTC
If any of your fields in an Archetype are marked as Required, it then essentially makes the entire Umbraco property required, forcing the user to add a fieldset.  IE, when you create a new page, it automatically has a blank Archetype in the "invalid" state, and you're forced to enter some data for the page to save.

In this case, I want the Umbraco property itself to be optional, but if the user enters data, I want to ensure the first field is filled out by requiring it.  For example, requiring a URL be entered but providing an optional Caption.

Currently it marks the entire Fieldset as invalid as soon as the page is created, thus forcing the user to enter data.

![2014-02-27_18-03-36](https://f.cloud.github.com/assets/1396376/2290116/3bd45254-a014-11e3-87c2-5bc23ae44f5a.png)

**Comment by kjac** [comment] 2017-02-15 20:34
The original issue can be handled by enabling "Start With Add Button?" in the "Global Fieldset Options".

I can't reproduce the issue reported by @bjarnef ... I'm going to close this now.

**Closed by kjac** 2017-02-15 20:34 UTC
Labels: bug
